import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import Providers from "@/utils/provider";
import Navbar from "./components/Nav/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <NextAuthProvider>
          <Navbar />
          <Providers>
            <main>{children}</main>
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}
